---
- name: "Check for snoopy installation"
  ansible.builtin.stat:
    path: '{{ _snoopy_exec_path }}/snoopyctl'
  changed_when: false
  register: snoopy_binary

- name: "Installation"
  when: not snoopy_binary.stat.exists or snoopy_force_install|bool
  block:
    - name: "DEBIAN-11/12 | Install requirements"
      ansible.builtin.package:
        name: libc6-dev
        state: present
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version >= '11'

    - name: "Download requirements"
      ansible.builtin.package:
        name: "{{ _snoopy_compile_pkg_install }}"
        state: present

    - name: "Unarchive source"
      ansible.builtin.unarchive:
        src: '{{ snoopy_url }}'
        dest: '{{ snoopy_tmp_dir }}'
        remote_src: true

    - name: "Run configure..."
      ansible.builtin.command: "./configure {{ snoopy_configure_options }}"
      args:
        chdir: '{{ snoopy_tmp_dir }}/{{ snoopy_build_dir }}'
      changed_when: false

    - name: "Run make..."
      community.general.make:
        chdir: '{{ snoopy_tmp_dir }}/{{ snoopy_build_dir }}'

    - name: "Run make install..."
      community.general.make:
        chdir: '{{ snoopy_tmp_dir }}/{{ snoopy_build_dir }}'
        target: install

    - name: "Create log file"
      ansible.builtin.file:
        path: /var/log/snoopy.log
        state: touch
        mode: '0644'

    - name: "Uninstall unnecessary requirements"
      ansible.builtin.package:
        name: "{{ _snoopy_compile_pkg_uninstall }}"
        state: absent
      when: snoopy_uninstall_pkg|bool

    - name: "Clean source files"
      ansible.builtin.file:
        path: "{{ snoopy_tmp_dir }}/{{ snoopy_build_dir }}"
        state: absent

- name: "Set config"
  ansible.builtin.lineinfile:
    dest: '{{ _snoopy_cfg_file }}'
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {regexp: "^output = file:", line: "output = file:{{ snoopy_log_file }}"}
    - {regexp: '^filter_chain =', line: 'filter_chain = "exclude_spawns_of:cron,my_daemon;only_tty"'}
    - {regexp: "^message_format =", line: 'message_format = "{{ snoopy_msg_format }}"'}
  notify:
    - stop snoopy
    - start snoopy

#- name: snoopy | Create a logrotate file
#  ansible.builtin.copy:
#    src: snoopy
#    dest: /etc/logrotate.d/snoopy
#    owner: root
#    group: root
#    mode: '0640'
