---
- name: "When major distrib is 8"
  when: ansible_distribution_major_version == '8'
  block:
    - name: "Install package"
      ansible.builtin.dnf:
        name: snoopy
        state: present

- name: "When major distrib is 8"
  when: ansible_distribution_major_version == '7'
  block:
    - name: "Install dependencies"
      ansible.builtin.dnf:
        name:
          - gcc
          - socat
        state: present

    - name: "Unarchive source"
      ansible.builtin.unarchive:
        src: '{{ snoopy_url }}'
        dest: '{{ snoopy_tmp_dir }}'
        remote_src: true

    - name: "Run configure..."
      ansible.builtin.command: ./configure
      args:
        chdir: '{{ snoopy_tmp_dir }}/{{ snoopy_build_dir }}'
      changed_when: false

    - name: "Run make..."
      community.general.make:
        chdir: '{{ snoopy_tmp_dir }}/{{ snoopy_build_dir }}'

    - name: "Run make install..."
      community.general.make:
        chdir: '{{ snoopy_tmp_dir }}/{{ snoopy_build_dir }}'
        target: install
