---
- when: ansible_distribution_major_version == '8'
  block:
    - name: "Install package"
      dnf:
        name: snoopy
        state: present

- when: ansible_distribution_major_version == '7'
  block:
    - name: "Install dependencies"
      dnf:
        name:
          - gcc
          - socat
        state: present

    - name: "Unarchive source"
      unarchive:
        src: '{{ snoopy_url }}'
        dest: '{{ snoopy_tmp_dir }}'
        remote_src: true

    - name: "Run configure..."
      command: ./configure
      args:
        chdir: '{{ snoopy_tmp_dir }}/{{ snoopy_build_dir }}'

    - name: "Run make..."
      make:
        chdir: '{{ snoopy_tmp_dir }}/{{ snoopy_build_dir }}'

    - name: "Run make install..."
      make:
        chdir: '{{ snoopy_tmp_dir }}/{{ snoopy_build_dir }}'
        target: install
